### ISSUE TITLE
skills on passive agression

### ISSUE THREAD

**Issue by Johaxan163** [yekoc/Risk-Of-Rain-2-Mods#13]
some skills on the passive agression feel quite underwhelming like the ones from voiddiend and artificier being strictly worthless to uses

**Comment by yekoc** [comment]
Balance considerations are a mix of me generally lacking a sense for it (I always prioritise feel over numbers) and the mod being WIP.
Artificer for example, is missing skills in what is supposed to be a very heavily synergistic set.
Viend specifically is a bit of a special case, because I learned quite a bit after I finished working on it that people seem to just have an entirely different read on how he works as a character than I do.In my experience the corrupted mode feels worse to use, thus it's either a punishment or a temporary burst of damage. The infestation carries on these properties of being both slightly annoying (it stops you and spawns enemies) but also having beneficial burst potential (it causes infighting/removes enemies from their teams), and the teleport turns into damage when corrupted because of the same viewpoint of the corruption serving as a temporary super mode.
If you have specific ideas feel free to put them either over at #3 or here and I'll give them a read.
Most mods _are_ also currently broken and I won't be able to get to fixing things for a slight bit due to afk concerns so it's both a good and bad time to discuss design.

**Comment by Johaxan163** [comment]
Well i will mostly talk about what could be done on voidfiend tear bc i feel like the changes propossed by other users are rigth, my main discomfort with the corrupted tear is that instead of being a simple copypaste of the void fog it should also scale with the damage of void fiend anf also have a radius to cast it around (maybe not that big bc the idea of it coming from voidfiend itself is kinda cool) but yeah is what i think it needs

**Comment by Johaxan163** [comment]
Also the self damage should be kept but instead scale at a lower number to not kill you instantly
