### ISSUE TITLE
Multiplayer Issues Encountered (As Player 2)

### ISSUE THREAD

**Issue by BungoDungo** [yekoc/Risk-Of-Rain-2-Mods#2]
Artificer's blood passive seemingly prevents the host having natural health regen, and the effect also extends to the equipping blood M1. 

Artificer's snow golem is unleavable as P2 and has no abilities. 

Engineer's passive occasionally throws errors in console and prevents picking items up.

[zipped_log.zip](https://github.com/yekoc/Risk-Of-Rain-2-Mods/files/10419607/zipped_log.zip)

I will be testing more later, but I have no idea if it's compatibility issues or not yet.

**Comment by yekoc** [comment]
Thanks for the report! (and especially for attaching the log to it)
Engi Passive is fixed in 8f13d29298c4cb56fa50235e80cd98acf6a9cbcb
Snow golem not having any abilities is intentional but not being able to leave it isn't
Blood M1 prevents regen when on cooldown but the passive shouldn't disable it,I'll investigate whether the effects leaks to other players.

**Comment by BungoDungo** [comment]
I really like this mod and am looking forward to incorporating it into my multiplayer modpack. I'll keep testing new updates as they come out so I can report when something breaks. 

I also had some comments on the actual design of some of the abilities that I wanted to share, but I didn't want to post it on the github, is there a preferred way of receiving user feedback like a discord or something?

**Comment by yekoc** [comment]
Feel free to leave feedback here or in #3 
Information tends to disappear in discord.

**Comment by yekoc** [comment]
Should be fixed in 1a1908b .
Please re-open the issue if it persists.
Thanks.
